language: bash
services: docker
before_install:
  - echo -e "Starting build..."
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push 080950/mysql-rest-with-spring-boot;
    docker push 080950/rest-with-spring-boot;
  on:
    branch: master
notifications:
  email: false
