version: '3.4'
services:
  db:
    image: 080950/mysql-rest-with-spring-boot   
    command: mysqld --default-authentication-plugin=mysql_native_password 
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_spring_boot
    ports:
      - "3308:3306"
    networks:
      - udemy-network 
  rest-with-spring-boot:
    image: 080950/rest-with-spring-boot  
    restart: always      
    build: ./users_simple_register
    working_dir: /users_simple_register 
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./users_simple_register:/users_simple_register
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run 
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge
